name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
    - name: Build standalone
      run: npm run build-standalone-prod
    - name: Upload standalone artifact
      uses: actions/upload-artifact@v2
      with:
        name: standalone
        path: dist/standalone.html
